# Generated by Django 5.2.11 on 2026-03-06 12:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название квеста')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('completed', 'Завершён'), ('failed', 'Провален')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный'), ('legendary', 'Легендарный')], default='easy', max_length=20, verbose_name='Сложность')),
                ('reward_gold', models.PositiveIntegerField(default=0, verbose_name='Награда (золото)')),
                ('reward_experience', models.PositiveIntegerField(default=0, verbose_name='Награда (опыт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата удаления')),
            ],
            options={
                'verbose_name': 'Квест',
                'verbose_name_plural': 'Квесты',
                'db_table': 'quests',
                'ordering': ['-created_at'],
            },
        ),
    ]
